"""
make_pricing_figures.py
=======================
Produce all chapter figures from the two Excel files generated by
compare_swapvol.py.

Figures produced
----------------
  fig_mae_heatmap.pdf          — (expiry × tenor) MAE heatmap, pre vs post Stage-2
  fig_vol_timeseries.pdf       — model vs market vol over time for representative
                                 buckets (default: 2Y×5Y, 5Y×5Y, 10Y×5Y),
                                 with vertical bar at train/test split
  fig_vol_scatter.pdf          — model vol vs market vol scatter, pre and post,
                                 coloured by expiry; 45° reference line included

Usage
-----
    python make_pricing_figures.py

Or call `run(pre_xlsx, post_xlsx, split_date, out_dir)` from another script.
"""

import os
import sys

try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.getcwd()

PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
THESIS_ROOT  = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
for p in [SCRIPT_DIR, PROJECT_ROOT, THESIS_ROOT]:
    if p not in sys.path:
        sys.path.insert(0, p)

import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# =============================================================================
# DEFAULTS — change here or override via run()
# =============================================================================
PRE_XLSX   = os.path.join(SCRIPT_DIR, "swapvol_results",
                          "swaption_vol_comparison_stage1.xlsx")
POST_XLSX  = os.path.join(SCRIPT_DIR, "swapvol_results",
                          "swaption_vol_comparison_stage2.xlsx")
SPLIT_DATE = "2018-12-31"        # ISO string or None
OUT_DIR    = os.path.join(THESIS_ROOT, "Figures", "Pricing")

# Buckets shown in the time-series panel
TS_BUCKETS = [(2, 5), (5, 5), (10, 5)]   # (expiry, tenor) pairs

# Expiry ordering for heatmap row/col labels
EXPIRIES = [1, 2, 5, 10]
TENORS   = [1, 2, 5, 10]


# =============================================================================
# HELPER — load one Excel and clean types
# =============================================================================

def _load(path: str) -> pd.DataFrame:
    df = pd.read_excel(path, engine="openpyxl")
    df["market_as_of_date"] = pd.to_datetime(df["market_as_of_date"]).dt.normalize()
    df["option_maturity"]   = df["option_maturity"].astype(int)
    df["swap_tenor"]        = df["swap_tenor"].astype(int)
    for col in ["market_vol_bp", "model_vol_bp", "vol_error_bp",
                "abs_vol_error_bp", "mc_se_vol_bp"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    if "split" not in df.columns:
        df["split"] = "all"
    return df


# =============================================================================
# 1.  MAE HEATMAP  (pre vs post, side by side)
# =============================================================================

def fig_mae_heatmap(df_pre, df_post, out_dir, split="all"):
    """
    Two-panel (expiry × tenor) heatmap of mean |vol error| in bp.
    Left panel  = Stage-1 (pre calibration).
    Right panel = Stage-2 (post calibration).
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5), constrained_layout=True)

    vmax = 0.0
    mats = []
    for df in (df_pre, df_post):
        sub = df if split == "all" else df[df["split"] == split]
        sub = sub.dropna(subset=["abs_vol_error_bp"])
        pivot = (sub.groupby(["option_maturity", "swap_tenor"])["abs_vol_error_bp"]
                    .mean()
                    .unstack("swap_tenor")
                    .reindex(index=EXPIRIES, columns=TENORS))
        mats.append(pivot)
        vmax = max(vmax, float(pivot.max(skipna=True).max(skipna=True)))

    titles = ["Pre Stage-2  (Stage-1 only)", "Post Stage-2  (calibrated)"]
    for ax, mat, title in zip(axes, mats, titles):
        vals = mat.values.astype(float)
        im = ax.imshow(vals, aspect="auto", origin="upper",
                       cmap="YlOrRd", vmin=0, vmax=vmax)
        ax.set_xticks(range(len(TENORS)))
        ax.set_xticklabels([f"{t}Y" for t in TENORS])
        ax.set_yticks(range(len(EXPIRIES)))
        ax.set_yticklabels([f"{e}Y" for e in EXPIRIES])
        ax.set_xlabel("Swap tenor")
        ax.set_ylabel("Option expiry")
        ax.set_title(title)
        for i in range(len(EXPIRIES)):
            for j in range(len(TENORS)):
                v = vals[i, j]
                if np.isfinite(v):
                    ax.text(j, i, f"{v:.0f}", ha="center", va="center",
                            fontsize=9,
                            color="white" if v > 0.6 * vmax else "black")
        plt.colorbar(im, ax=ax, label="MAE (bp)")

    tag = f" [{split}]" if split != "all" else ""
    fig.suptitle(f"ATM Swaption Vol Error — Mean Absolute Error (bp){tag}", y=1.02)
    path = os.path.join(out_dir, f"fig_mae_heatmap{'_' + split if split != 'all' else ''}.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# 2.  TIME-SERIES  (model vs market, selected buckets)
# =============================================================================

def fig_vol_timeseries(df_pre, df_post, out_dir, split_date=None,
                       buckets=TS_BUCKETS):
    """
    For each (expiry, tenor) bucket: plot market vol, pre-Stage-2 vol,
    post-Stage-2 vol over the full date range.  Shade the test period.
    """
    n = len(buckets)
    fig, axes = plt.subplots(n, 1, figsize=(12, 3.5 * n), constrained_layout=True)
    if n == 1:
        axes = [axes]

    split_ts = pd.Timestamp(split_date).normalize() if split_date else None

    for ax, (exp, ten) in zip(axes, buckets):
        mask_pre  = (df_pre["option_maturity"]  == exp) & (df_pre["swap_tenor"]  == ten)
        mask_post = (df_post["option_maturity"] == exp) & (df_post["swap_tenor"] == ten)

        sub_pre  = df_pre[mask_pre].sort_values("market_as_of_date")
        sub_post = df_post[mask_post].sort_values("market_as_of_date")

        dates_pre   = sub_pre["market_as_of_date"]
        mkt_pre     = sub_pre["market_vol_bp"]
        model_pre   = sub_pre["model_vol_bp"]
        model_post  = sub_post.set_index("market_as_of_date")["model_vol_bp"].reindex(dates_pre).values

        ax.plot(dates_pre, mkt_pre,    color="black",  lw=1.5, label="Market")
        ax.plot(dates_pre, model_pre,  color="#1f77b4", lw=1.2, ls="--", label="Model (pre Stage-2)")
        ax.plot(dates_pre, model_post, color="#d62728", lw=1.2, ls="-",  label="Model (post Stage-2)")

        if split_ts is not None:
            xmin, xmax = ax.get_xlim()
            ymin, ymax = ax.get_ylim()
            ax.axvline(split_ts, color="gray", lw=1, ls=":")
            # Shade the test region to the right of the split
            ax.axvspan(split_ts, dates_pre.max(), alpha=0.06, color="gray",
                       label="Test period")

        ax.set_title(f"{exp}Y × {ten}Y swaption — normal vol (bp)")
        ax.set_ylabel("Normal vol (bp)")
        ax.legend(fontsize=8, ncol=2)
        ax.grid(True, alpha=0.25)

    axes[-1].set_xlabel("Date")
    path = os.path.join(out_dir, "fig_vol_timeseries.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# 3.  SCATTER  (model vol vs market vol, pre and post, coloured by expiry)
# =============================================================================

def fig_vol_scatter(df_pre, df_post, out_dir):
    """
    Scatter of model_vol_bp vs market_vol_bp for pre and post calibration.
    Points coloured by expiry.  45° reference line shown.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 5.5), constrained_layout=True)

    expiry_colors = {1: "#1f77b4", 2: "#ff7f0e", 5: "#2ca02c", 10: "#d62728"}
    legend_patches = [mpatches.Patch(color=c, label=f"{e}Y expiry")
                      for e, c in expiry_colors.items()]

    for ax, df, title in [
        (axes[0], df_pre,  "Pre Stage-2  (Stage-1 only)"),
        (axes[1], df_post, "Post Stage-2  (calibrated)"),
    ]:
        sub = df.dropna(subset=["model_vol_bp", "market_vol_bp"])
        colors = sub["option_maturity"].map(expiry_colors).fillna("gray")

        ax.scatter(sub["market_vol_bp"], sub["model_vol_bp"],
                   c=colors, alpha=0.55, s=18, linewidths=0)

        lo = min(sub["market_vol_bp"].min(), sub["model_vol_bp"].min()) * 0.9
        hi = max(sub["market_vol_bp"].max(), sub["model_vol_bp"].max()) * 1.05
        ax.plot([lo, hi], [lo, hi], "k--", lw=0.9, label="45° line")

        ax.set_xlabel("Market vol (bp)")
        ax.set_ylabel("Model vol (bp)")
        ax.set_title(title)
        ax.legend(handles=legend_patches + [
            plt.Line2D([0], [0], color="k", lw=0.9, ls="--", label="45° line")
        ], fontsize=8)
        ax.grid(True, alpha=0.25)

    fig.suptitle("ATM Swaption: Model vol vs Market vol")
    path = os.path.join(out_dir, "fig_vol_scatter.pdf")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# ENTRY POINT
# =============================================================================

def run(
    pre_xlsx   = PRE_XLSX,
    post_xlsx  = POST_XLSX,
    split_date = SPLIT_DATE,
    out_dir    = OUT_DIR,
    buckets    = TS_BUCKETS,
):
    os.makedirs(out_dir, exist_ok=True)

    print(f"Loading pre  : {pre_xlsx}")
    df_pre  = _load(pre_xlsx)
    print(f"Loading post : {post_xlsx}")
    df_post = _load(post_xlsx)

    print(f"\nPre  shape : {df_pre.shape}   valid model rows : "
          f"{df_pre['model_vol_bp'].notna().sum()}")
    print(f"Post shape : {df_post.shape}  valid model rows : "
          f"{df_post['model_vol_bp'].notna().sum()}")

    # ── Heatmaps ──────────────────────────────────────────────────────
    fig_mae_heatmap(df_pre, df_post, out_dir, split="all")
    if split_date is not None:
        for sp in ["train", "test"]:
            if (df_pre["split"] == sp).any():
                fig_mae_heatmap(df_pre, df_post, out_dir, split=sp)

    # ── Time-series ───────────────────────────────────────────────────
    # Keep only buckets that have data
    available_buckets = [
        (e, t) for e, t in buckets
        if ((df_pre["option_maturity"] == e) & (df_pre["swap_tenor"] == t)).any()
    ]
    if available_buckets:
        fig_vol_timeseries(df_pre, df_post, out_dir,
                           split_date=split_date, buckets=available_buckets)
    else:
        warnings.warn("No matching (expiry, tenor) buckets found for time-series figure.",
                      RuntimeWarning)

    # ── Scatter ───────────────────────────────────────────────────────
    fig_vol_scatter(df_pre, df_post, out_dir)

    print(f"\nAll figures written to: {out_dir}")


if __name__ == "__main__":
    run()


