"""
make_pricing_figures.py
=======================
Produce all chapter figures from Excel files generated by compare_swapvol.py
and CSV files from test_greeks.py.

Supports comparing multiple checkpoints (e.g., baseline vs joint training).

Figures produced
----------------
  fig_mae_heatmap_{label}.pdf         — (expiry × tenor) MAE heatmap comparison
  fig_vol_timeseries_{label}.pdf      — model vs market vol over time
  fig_vol_scatter_{label}.pdf         — model vol vs market vol scatter
  fig_greeks_comparison_{label}.pdf   — Greeks comparison across models

Usage
-----
    # Compare two models
    python make_pricing_figures.py \\
        --files checkpoint_dim4_ep3500 checkpoint_baseline_ep3500 \\
        --labels "Joint Training" "Baseline"
    
    # Single model
    python make_pricing_figures.py --files checkpoint_dim4_ep3500 --labels "My Model"

Or call run(files, labels, split_date, out_dir) from another script.
"""

import os
import sys
import argparse

try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.getcwd()

PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
THESIS_ROOT  = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
for p in [SCRIPT_DIR, PROJECT_ROOT, THESIS_ROOT]:
    if p not in sys.path:
        sys.path.insert(0, p)

import warnings
import glob
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# =============================================================================
# DEFAULTS
# =============================================================================
OUT_DIR = os.path.join(THESIS_ROOT, "Figures", "Pricing")


# =============================================================================
# HELPERS — locate output files produced by compare_swapvol.py / test_greeks.py
# =============================================================================

def _find_swapvol_file(checkpoint_name: str, search_dir: str) -> str:
    """
    Return the path of the Excel file produced by compare_swapvol.py for
    *checkpoint_name*.  Searches *search_dir* for
    ``swaption_vol_comparison_<checkpoint_name>.xlsx``.

    Raises FileNotFoundError if not found.
    """
    candidate = os.path.join(search_dir, f"swaption_vol_comparison_{checkpoint_name}.xlsx")
    if os.path.isfile(candidate):
        return candidate

    # Fallback: glob for any file containing the checkpoint name
    matches = glob.glob(os.path.join(search_dir, f"*{checkpoint_name}*.xlsx"))
    vol_matches = [m for m in matches if "vol_comparison" in os.path.basename(m)]
    if vol_matches:
        return vol_matches[0]

    raise FileNotFoundError(
        f"No swaption_vol_comparison Excel found for '{checkpoint_name}' in {search_dir!r}"
    )


def _find_greeks_files(checkpoint_name: str, search_dir: str) -> list:
    """
    Return a list of CSV paths produced by test_greeks.py for *checkpoint_name*.
    Returns an empty list (not an error) when none are found.
    """
    pattern = os.path.join(search_dir, f"greeks_{checkpoint_name}_*.csv")
    return sorted(glob.glob(pattern))

# Buckets shown in the time-series panel
TS_BUCKETS = [(2, 5), (5, 5), (10, 5)]   # (expiry, tenor) pairs

# Expiry ordering for heatmap row/col labels
EXPIRIES = [1, 2, 5, 10]
TENORS   = [1, 2, 5, 10]


# =============================================================================
# HELPER — load one Excel and clean types
# =============================================================================

def _load(path: str) -> pd.DataFrame:
    df = pd.read_excel(path, engine="openpyxl")
    df["market_as_of_date"] = pd.to_datetime(df["market_as_of_date"]).dt.normalize()
    df["option_maturity"]   = df["option_maturity"].astype(int)
    df["swap_tenor"]        = df["swap_tenor"].astype(int)
    for col in ["market_vol_bp", "model_vol_bp", "vol_error_bp",
                "abs_vol_error_bp", "mc_se_vol_bp"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    if "split" not in df.columns:
        df["split"] = "all"
    return df


# =============================================================================
# 1.  MAE HEATMAP  (multiple models, side by side)
# =============================================================================

def fig_mae_heatmap(dataframes, labels, out_dir, split="all", tag=""):
    """
    Multi-panel (expiry × tenor) heatmap of mean |vol error| in bp.
    Each panel = one model.
    """
    n_models = len(dataframes)
    fig, axes = plt.subplots(1, n_models, figsize=(6 * n_models, 4.5), constrained_layout=True)
    if n_models == 1:
        axes = [axes]

    vmax = 0.0
    mats = []
    for df in dataframes:
        sub = df if split == "all" else df[df["split"] == split]
        sub = sub.dropna(subset=["abs_vol_error_bp"])
        pivot = (sub.groupby(["option_maturity", "swap_tenor"])["abs_vol_error_bp"]
                    .mean()
                    .unstack("swap_tenor")
                    .reindex(index=EXPIRIES, columns=TENORS))
        mats.append(pivot)
        vmax = max(vmax, float(pivot.max(skipna=True).max(skipna=True)))

    for ax, mat, label in zip(axes, mats, labels):
        vals = mat.values.astype(float)
        im = ax.imshow(vals, aspect="auto", origin="upper",
                       cmap="YlOrRd", vmin=0, vmax=vmax)
        ax.set_xticks(range(len(TENORS)))
        ax.set_xticklabels([f"{t}Y" for t in TENORS])
        ax.set_yticks(range(len(EXPIRIES)))
        ax.set_yticklabels([f"{e}Y" for e in EXPIRIES])
        ax.set_xlabel("Swap tenor")
        ax.set_ylabel("Option expiry")
        ax.set_title(label)
        for i in range(len(EXPIRIES)):
            for j in range(len(TENORS)):
                v = vals[i, j]
                if np.isfinite(v):
                    ax.text(j, i, f"{v:.0f}", ha="center", va="center",
                            fontsize=9,
                            color="white" if v > 0.6 * vmax else "black")
        plt.colorbar(im, ax=ax, label="MAE (bp)")

    split_tag = f" [{split}]" if split != "all" else ""
    fig.suptitle(f"ATM Swaption Vol Error — Mean Absolute Error (bp){split_tag}", y=1.02)
    filename = f"fig_mae_heatmap{tag}{'_' + split if split != 'all' else ''}.pdf"
    path = os.path.join(out_dir, filename)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# 2.  TIME-SERIES  (model vs market, selected buckets, multiple models)
# =============================================================================

def fig_vol_timeseries(dataframes, labels, out_dir, split_date=None,
                       buckets=TS_BUCKETS, tag=""):
    """
    For each (expiry, tenor) bucket: plot market vol + all model vols over time.
    Shade the test period if split_date is given.
    """
    n = len(buckets)
    fig, axes = plt.subplots(n, 1, figsize=(12, 3.5 * n), constrained_layout=True)
    if n == 1:
        axes = [axes]

    split_ts = pd.Timestamp(split_date).normalize() if split_date else None
    colors = plt.cm.tab10(np.linspace(0, 1, len(dataframes)))

    for ax, (exp, ten) in zip(axes, buckets):
        # Plot market from first dataframe
        df_first = dataframes[0]
        mask = (df_first["option_maturity"] == exp) & (df_first["swap_tenor"] == ten)
        sub_first = df_first[mask].sort_values("market_as_of_date")
        dates = sub_first["market_as_of_date"]
        mkt_vol = sub_first["market_vol_bp"]
        
        ax.plot(dates, mkt_vol, color="black", lw=1.5, label="Market", zorder=10)

        # Plot each model
        for df, label, color in zip(dataframes, labels, colors):
            mask = (df["option_maturity"] == exp) & (df["swap_tenor"] == ten)
            sub = df[mask].sort_values("market_as_of_date")
            model_vol = sub.set_index("market_as_of_date")["model_vol_bp"].reindex(dates).values
            ax.plot(dates, model_vol, color=color, lw=1.2, ls="--", label=label)

        if split_ts is not None and len(dates) > 0:
            ax.axvline(split_ts, color="gray", lw=1, ls=":")
            ax.axvspan(split_ts, dates.max(), alpha=0.06, color="gray", label="Test period")

        ax.set_title(f"{exp}Y × {ten}Y swaption — normal vol (bp)")
        ax.set_ylabel("Normal vol (bp)")
        ax.legend(fontsize=8, ncol=min(3, len(labels) + 2))
        ax.grid(True, alpha=0.25)

    axes[-1].set_xlabel("Date")
    filename = f"fig_vol_timeseries{tag}.pdf"
    path = os.path.join(out_dir, filename)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# 3.  SCATTER  (model vol vs market vol, multiple models)
# =============================================================================

def fig_vol_scatter(dataframes, labels, out_dir, tag=""):
    """
    Scatter of model_vol_bp vs market_vol_bp for each model.
    Points coloured by expiry.  45° reference line shown.
    """
    n_models = len(dataframes)
    fig, axes = plt.subplots(1, n_models, figsize=(6 * n_models, 5.5), constrained_layout=True)
    if n_models == 1:
        axes = [axes]

    expiry_colors = {1: "#1f77b4", 2: "#ff7f0e", 5: "#2ca02c", 10: "#d62728"}
    legend_patches = [mpatches.Patch(color=c, label=f"{e}Y expiry")
                      for e, c in expiry_colors.items()]

    for ax, df, label in zip(axes, dataframes, labels):
        sub = df.dropna(subset=["model_vol_bp", "market_vol_bp"])
        colors = sub["option_maturity"].map(expiry_colors).fillna("gray")

        ax.scatter(sub["market_vol_bp"], sub["model_vol_bp"],
                   c=colors, alpha=0.55, s=18, linewidths=0)

        lo = min(sub["market_vol_bp"].min(), sub["model_vol_bp"].min()) * 0.9
        hi = max(sub["market_vol_bp"].max(), sub["model_vol_bp"].max()) * 1.05
        ax.plot([lo, hi], [lo, hi], "k--", lw=0.9, label="45° line")

        ax.set_xlabel("Market vol (bp)")
        ax.set_ylabel("Model vol (bp)")
        ax.set_title(label)
        ax.legend(handles=legend_patches + [
            plt.Line2D([0], [0], color="k", lw=0.9, ls="--", label="45° line")
        ], fontsize=8)
        ax.grid(True, alpha=0.25)

    fig.suptitle("ATM Swaption: Model vol vs Market vol")
    filename = f"fig_vol_scatter{tag}.pdf"
    path = os.path.join(out_dir, filename)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# 4.  GREEKS COMPARISON (compare Greeks across models)
# =============================================================================

def fig_greeks_comparison(greeks_files_list, labels, out_dir, tag=""):
    """
    Compare Greeks (delta, vega, gamma) across models.
    greeks_files_list: list of lists of CSV file paths for each model
    """
    if not greeks_files_list or all(len(files) == 0 for files in greeks_files_list):
        print("No Greeks files found - skipping Greeks comparison figure")
        return None

    # Load all Greeks data
    all_data = []
    for files, label in zip(greeks_files_list, labels):
        if not files:
            continue
        # Take the first file if multiple dates
        df = pd.read_csv(files[0])
        df["model"] = label
        all_data.append(df)
    
    if not all_data:
        print("No valid Greeks data - skipping Greeks comparison figure")
        return None
    
    df_all = pd.concat(all_data, ignore_index=True)
    
    # Create identifier for each (expiry, tenor) pair
    df_all["cell"] = df_all["expiry"].astype(str) + "Y×" + df_all["tenor"].astype(str) + "Y"
    
    # Plot delta, vega, gamma comparison
    fig, axes = plt.subplots(2, 2, figsize=(14, 10), constrained_layout=True)
    
    greek_cols = [("delta", "Delta"), ("vega", "Vega"), ("gamma", "Gamma"), ("dv01", "DV01")]
    
    for ax, (col, title) in zip(axes.flat, greek_cols):
        cells = df_all["cell"].unique()
        x = np.arange(len(cells))
        width = 0.8 / len(labels)
        
        for i, label in enumerate(labels):
            sub = df_all[df_all["model"] == label]
            values = [sub[sub["cell"] == cell][col].values[0] if len(sub[sub["cell"] == cell]) > 0 
                     else 0 for cell in cells]
            ax.bar(x + i * width, values, width, label=label, alpha=0.8)
        
        ax.set_xlabel("Swaption")
        ax.set_ylabel(title)
        ax.set_title(f"{title} Comparison")
        ax.set_xticks(x + width * (len(labels) - 1) / 2)
        ax.set_xticklabels(cells, rotation=45, ha="right")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.25, axis='y')
    
    fig.suptitle("Greeks Comparison Across Models (ATM Swaptions)", fontsize=14)
    filename = f"fig_greeks_comparison{tag}.pdf"
    path = os.path.join(out_dir, filename)
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved → {path}")
    return path


# =============================================================================
# ENTRY POINT
# =============================================================================

def run(
    checkpoint_names,
    labels=None,
    split_date=None,
    out_dir=OUT_DIR,
    buckets=TS_BUCKETS,
):
    """
    Generate all comparison figures for multiple checkpoints.
    
    Args:
        checkpoint_names: list of checkpoint names (without extension)
        labels: list of human-readable labels for each model
        split_date: train/test split date (ISO string or None)
        out_dir: output directory
        buckets: list of (expiry, tenor) tuples for time-series plots
    """
    os.makedirs(out_dir, exist_ok=True)

    if labels is None:
        labels = checkpoint_names

    if len(checkpoint_names) != len(labels):
        raise ValueError(f"Number of checkpoint_names ({len(checkpoint_names)}) must match number of labels ({len(labels)})")

    # Load swapvol data
    dataframes = []
    for name in checkpoint_names:
        try:
            xlsx_path = _find_swapvol_file(name, out_dir)
            print(f"Loading {name}: {xlsx_path}")
            df = _load(xlsx_path)
            dataframes.append(df)
        except FileNotFoundError as e:
            print(f"Warning: {e}")
            print(f"Skipping {name}")
    
    if not dataframes:
        print("ERROR: No swapvol files found!")
        return
    
    # Update labels if some files were skipped
    if len(dataframes) < len(checkpoint_names):
        loaded = []
        for i, name in enumerate(checkpoint_names):
            try:
                _find_swapvol_file(name, out_dir)
                loaded.append(labels[i])
            except FileNotFoundError:
                pass
        labels = loaded

    print(f"\nLoaded {len(dataframes)} swapvol files")
    for df, label in zip(dataframes, labels):
        print(f"  {label}: {df.shape[0]} rows, {df['model_vol_bp'].notna().sum()} valid model vols")

    # Create tag from checkpoint names
    tag = "_vs_".join(checkpoint_names[:2]) if len(checkpoint_names) <= 2 else f"_{len(checkpoint_names)}models"

    # ── Heatmaps ──────────────────────────────────────────────────────
    fig_mae_heatmap(dataframes, labels, out_dir, split="all", tag=f"_{tag}")
    if split_date is not None:
        for sp in ["train", "test"]:
            if any((df["split"] == sp).any() for df in dataframes):
                fig_mae_heatmap(dataframes, labels, out_dir, split=sp, tag=f"_{tag}")

    # ── Time-series ───────────────────────────────────────────────────
    # Keep only buckets that have data in first dataframe
    available_buckets = [
        (e, t) for e, t in buckets
        if ((dataframes[0]["option_maturity"] == e) & (dataframes[0]["swap_tenor"] == t)).any()
    ]
    if available_buckets:
        fig_vol_timeseries(dataframes, labels, out_dir,
                          split_date=split_date, buckets=available_buckets, tag=f"_{tag}")
    else:
        warnings.warn("No matching (expiry, tenor) buckets found for time-series figure.",
                     RuntimeWarning)

    # ── Scatter ───────────────────────────────────────────────────────
    fig_vol_scatter(dataframes, labels, out_dir, tag=f"_{tag}")

    # ── Greeks comparison ─────────────────────────────────────────────
    greeks_files_list = []
    for name in checkpoint_names:
        try:
            files = _find_greeks_files(name, out_dir)
            greeks_files_list.append(files)
            if files:
                print(f"Found {len(files)} Greeks file(s) for {name}")
        except Exception as e:
            print(f"No Greeks files for {name}: {e}")
            greeks_files_list.append([])
    
    fig_greeks_comparison(greeks_files_list, labels, out_dir, tag=f"_{tag}")

    print(f"\nAll figures written to: {out_dir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate pricing comparison figures")
    parser.add_argument("--files", nargs="+", required=True,
                       help="Checkpoint names (e.g., checkpoint_dim4_ep3500)")
    parser.add_argument("--labels", nargs="+", default=None,
                       help="Labels for each model (optional)")
    parser.add_argument("--split_date", type=str, default=None,
                       help="Train/test split date (YYYY-MM-DD)")
    parser.add_argument("--out_dir", type=str, default=OUT_DIR,
                       help=f"Output directory (default: {OUT_DIR})")
    
    args = parser.parse_args()
    
    run(
        checkpoint_names=args.files,
        labels=args.labels,
        split_date=args.split_date,
        out_dir=args.out_dir,
    )


