"""
plot_valid_path_fraction.py
============================

Generate a heatmap and/or table showing the fraction of simulated paths
that produce finite decoder outputs for each (expiry, tenor) combination.

This diagnostic quantifies the path-exclusion issue mentioned in the
pricing chapter: approximately 30% of simulated paths yield non-finite
bond prices and must be excluded from the Monte Carlo calculation.

Reads:
    Figures/PricingResults/Diagnostics/EUR_dim4_stable/plots/pricing_distribution.csv

Outputs:
    Figures/PricingResults/Diagnostics/EUR_dim4_stable/plots/valid_path_fraction.png
    Figures/PricingResults/Diagnostics/EUR_dim4_stable/plots/valid_path_fraction_table.tex

Usage:
    python Code/Pricing/plot_valid_path_fraction.py
"""

from __future__ import annotations
import csv
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Configuration
CCY = "EUR"
LATENT_DIM = 4
VARIANT = "stable"
N_PATHS = 10_000

EXPIRIES = [1, 5, 10]
TENORS = [1, 5, 10]


def main():
    # Paths
    base = Path(__file__).resolve().parents[2]
    csv_path = (
        base / "Figures" / "PricingResults" / "Diagnostics"
        / f"{CCY}_dim{LATENT_DIM}_{VARIANT}" / "plots"
        / "pricing_distribution.csv"
    )
    out_dir = csv_path.parent
    out_png = out_dir / "valid_path_fraction.png"
    out_tex = out_dir / "valid_path_fraction_table.tex"

    if not csv_path.exists():
        print(f"ERROR: {csv_path} not found.")
        print("Run plot_pricing_distribution.py first.")
        return 1

    # Read CSV
    rows = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    # Aggregate across dates for each (expiry, tenor)
    data = {}
    for row in rows:
        exp = int(row["expiry"])
        ten = int(row["tenor"])
        n_valid = int(row["n_valid"])
        
        key = (exp, ten)
        if key not in data:
            data[key] = []
        data[key].append(n_valid)

    # Compute mean fraction for each cell
    fraction_matrix = np.zeros((len(EXPIRIES), len(TENORS)))
    for i, exp in enumerate(EXPIRIES):
        for j, ten in enumerate(TENORS):
            key = (exp, ten)
            if key in data:
                mean_valid = np.mean(data[key])
                fraction_matrix[i, j] = mean_valid / N_PATHS
            else:
                fraction_matrix[i, j] = np.nan

    # Overall average
    overall_fraction = np.nanmean(fraction_matrix)
    overall_excluded = 1.0 - overall_fraction

    print(f"Valid path fraction matrix (rows=expiry, cols=tenor):")
    print(f"         Tenor:  1Y      5Y     10Y")
    for i, exp in enumerate(EXPIRIES):
        print(f"Expiry {exp:2d}Y:    ", end="")
        for j in range(len(TENORS)):
            frac = fraction_matrix[i, j]
            if np.isnan(frac):
                print("   --   ", end="")
            else:
                print(f"{frac:6.2%}  ", end="")
        print()
    print(f"\nOverall average valid fraction:   {overall_fraction:.2%}")
    print(f"Overall average excluded fraction: {overall_excluded:.2%}")

    # --- Generate heatmap figure ---
    fig, ax = plt.subplots(figsize=(6, 5))
    
    # Convert to percentage for display
    fraction_pct = fraction_matrix * 100
    
    sns.heatmap(
        fraction_pct,
        annot=True,
        fmt=".1f",
        cmap="RdYlGn",
        vmin=60,
        vmax=80,
        cbar_kws={'label': 'Valid path fraction (%)'},
        xticklabels=[f"{t}Y" for t in TENORS],
        yticklabels=[f"{e}Y" for e in EXPIRIES],
        ax=ax,
        linewidths=0.5,
        linecolor='gray'
    )
    
    ax.set_xlabel("Underlying swap tenor", fontsize=11)
    ax.set_ylabel("Option expiry", fontsize=11)
    ax.set_title(
        f"Fraction of simulated paths with finite decoder output\n"
        f"{CCY} dim-{LATENT_DIM} {VARIANT}, {N_PATHS:,} paths per date, "
        f"average across pricing dates",
        fontsize=11
    )
    
    fig.tight_layout()
    fig.savefig(out_png, dpi=200, bbox_inches='tight')
    plt.close(fig)
    print(f"\nSaved figure: {out_png}")

    # --- Generate LaTeX table ---
    excluded_matrix = (1.0 - fraction_matrix) * 100
    
    with open(out_tex, "w") as f:
        f.write("% Auto-generated by plot_valid_path_fraction.py\n")
        f.write("\\begin{table}[htbp]\n")
        f.write("\\centering\n")
        f.write("\\caption{Fraction of simulated paths excluded owing to non-finite "
                f"decoder outputs. Values are percentages, averaged across {len(set(row['date'] for row in rows))} "
                "pricing dates.}\n")
        f.write("\\label{tab:excluded_path_fraction}\n")
        f.write("\\begin{tabular}{lccc}\n")
        f.write("\\hline\n")
        f.write("Option expiry & \\multicolumn{3}{c}{Underlying swap tenor} \\\\\n")
        f.write("              & 1Y & 5Y & 10Y \\\\\n")
        f.write("\\hline\n")
        
        for i, exp in enumerate(EXPIRIES):
            f.write(f"{exp}Y")
            for j in range(len(TENORS)):
                excl = excluded_matrix[i, j]
                if np.isnan(excl):
                    f.write(" & -- ")
                else:
                    f.write(f" & {excl:.1f}\\%")
            f.write(" \\\\\n")
        
        f.write("\\hline\n")
        f.write(f"\\multicolumn{{4}}{{l}}{{Overall average excluded: "
                f"{overall_excluded*100:.1f}\\%}} \\\\\n")
        f.write("\\hline\n")
        f.write("\\end{tabular}\n")
        f.write("\\end{table}\n")
    
    print(f"Saved LaTeX table: {out_tex}")
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

